/*
 * WiiFur
 * By Rainbain
 * Nov 5, 2023
 *
 * Sphere
 * This file was autogenerated by me.
*/

#include "MathUtil.h"

extern const uint16_t Sphere_NumVerts;
extern const guVector Sphere_Vertices[];
extern const guVector Sphere_Normals[];
extern const UV Sphere_UVs[];